name = "mx1"
main = "src/index.js"
compatibility_date = "2026-09-03"

[observability]
enabled = true

[vars]
PLATFORM_NAME = "mx1-integration-hub"
AI_MODULE = "mx2"
MX3_MODEL = "gpt-5-mini"
GEMINI_MODEL = "gemini-2.5-flash"
SUPABASE_URL = "https://tbiwgoklwgqrudjmflgb.supabase.co"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_lwzIuHxm3PYFb7CHCba9PA_xMp4oKHD"
SUPABASE_JWKS_URL = "https://tbiwgoklwgqrudjmflgb.supabase.co/auth/v1/.well-known/jwks.json"

[ai]
binding = "AI"

[assets]
directory = "../public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "APPS"
id = "74928e8799ab4cf88bf4a6cb83e098d5"

[[kv_namespaces]]
binding = "DEPLOYMENTS"
id = "772d2208ab0b4727915b17f409133c63"

[[d1_databases]]
binding = "DB"
database_name = "xm1"
database_id = "d06aaa8f-e765-4d37-9334-f614c5dec85e"
# id = "..."
# [[kv_namespaces]]
# binding = "DEPLOYMENTS"
# id = "..."
# [[d1_databases]]
# binding = "DB"
# database_name = "mx1-database"
# database_id = "..."

